Document: sublime
Title: Debian sublime Manual
Author: <insert document author here>
Abstract: This manual describes what sublime is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sublime/sublime.sgml.gz

Format: postscript
Files: /usr/share/doc/sublime/sublime.ps.gz

Format: text
Files: /usr/share/doc/sublime/sublime.text.gz

Format: HTML
Index: /usr/share/doc/sublime/html/index.html
Files: /usr/share/doc/sublime/html/*.html
